// <auto-generated />
using BusinessDirectory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BusinessDirectory.solution.Migrations
{
    [DbContext(typeof(BusinessDirectoryContext))]
    [Migration("20220819172510_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BusinessDirectory.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BusinessWebsite")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            BusinessName = "Malka",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://malkapdx.com/"
                        },
                        new
                        {
                            BusinessId = 2,
                            BusinessName = "Gracie's Apizza",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.graciesapizza.com/"
                        },
                        new
                        {
                            BusinessId = 3,
                            BusinessName = "Bing Mi",
                            BusinessType = "Food Cart",
                            BusinessWebsite = "https://www.bingmipdx.com/"
                        },
                        new
                        {
                            BusinessId = 4,
                            BusinessName = "St. Jack",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://stjackpdx.com//"
                        },
                        new
                        {
                            BusinessId = 5,
                            BusinessName = "Ringside Steakhouse",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.ringsidesteakhouse.com/"
                        },
                        new
                        {
                            BusinessId = 6,
                            BusinessName = "Toki",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.tokipdx.com/"
                        },
                        new
                        {
                            BusinessId = 7,
                            BusinessName = "Mucca Osteria",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://muccaosteria.com/"
                        },
                        new
                        {
                            BusinessId = 8,
                            BusinessName = "Republica",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://republicapdx.square.site/"
                        },
                        new
                        {
                            BusinessId = 9,
                            BusinessName = "Murata Restaurant",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.muratarestaurant.com/"
                        },
                        new
                        {
                            BusinessId = 10,
                            BusinessName = "Lovely's Fifty Fifty",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.lovelysfiftyfifty.com/"
                        },
                        new
                        {
                            BusinessId = 11,
                            BusinessName = "Casa Zoraya",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.casazorayapdx.com/"
                        },
                        new
                        {
                            BusinessId = 12,
                            BusinessName = "Kabba’s Kitchen",
                            BusinessType = "Food Cart",
                            BusinessWebsite = "http://kabbaskitchen.com/?utm_source=gmb&utm_medium=referral"
                        },
                        new
                        {
                            BusinessId = 13,
                            BusinessName = "Eem",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.eempdx.com/"
                        },
                        new
                        {
                            BusinessId = 14,
                            BusinessName = "Erica's Soul Food",
                            BusinessType = "Food Cart",
                            BusinessWebsite = "https://repuhttp://www.ericassoulfood.com/blicapdx.square.site/"
                        },
                        new
                        {
                            BusinessId = 15,
                            BusinessName = "Kee’s Loaded Kitchen",
                            BusinessType = "Food Cart",
                            BusinessWebsite = "https://www.instagram.com/keesloadedkitchen/"
                        },
                        new
                        {
                            BusinessId = 16,
                            BusinessName = "Berlu",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.berlupdx.com//"
                        },
                        new
                        {
                            BusinessId = 17,
                            BusinessName = "Nong's Khao Man Gai",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.khaomangai.com/"
                        },
                        new
                        {
                            BusinessId = 18,
                            BusinessName = "Le Pigeon",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.lepigeon.com/"
                        },
                        new
                        {
                            BusinessId = 19,
                            BusinessName = "Matta",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://mattapdx.com/"
                        },
                        new
                        {
                            BusinessId = 20,
                            BusinessName = "Scotch Lodge",
                            BusinessType = "Bar",
                            BusinessWebsite = "http://scotchlodge.com/"
                        },
                        new
                        {
                            BusinessId = 21,
                            BusinessName = "Normandie",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.normandiepdx.com/"
                        },
                        new
                        {
                            BusinessId = 22,
                            BusinessName = "Kachka",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://kachkapdx.com/"
                        },
                        new
                        {
                            BusinessId = 23,
                            BusinessName = "Hat Yai",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.hatyaipdx.com/"
                        },
                        new
                        {
                            BusinessId = 24,
                            BusinessName = "Nimblefish",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.nimblefishpdx.com/"
                        },
                        new
                        {
                            BusinessId = 25,
                            BusinessName = "Quaintrelle",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.quaintrelle.co/"
                        },
                        new
                        {
                            BusinessId = 26,
                            BusinessName = "Jacqueline",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.jacquelinepdx.com/"
                        },
                        new
                        {
                            BusinessId = 27,
                            BusinessName = "Mirisata",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.mirisata.com/"
                        },
                        new
                        {
                            BusinessId = 28,
                            BusinessName = "Magna Kusina",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.magnapdx.com/"
                        },
                        new
                        {
                            BusinessId = 29,
                            BusinessName = "Ripe Cooperative",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.ripecooperative.com/"
                        },
                        new
                        {
                            BusinessId = 30,
                            BusinessName = "Urdaneta",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://urdanetapdx.com/"
                        },
                        new
                        {
                            BusinessId = 31,
                            BusinessName = "Oma's Hideaway",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://omashideaway.com/"
                        },
                        new
                        {
                            BusinessId = 32,
                            BusinessName = "Cafe Rowan",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://www.caferowan.com/"
                        },
                        new
                        {
                            BusinessId = 33,
                            BusinessName = "Kim Jong Grillin",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://kjgpdx.com/"
                        },
                        new
                        {
                            BusinessId = 34,
                            BusinessName = "Dirty Lettuce",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "http://dirtylettuce.square.site/"
                        },
                        new
                        {
                            BusinessId = 35,
                            BusinessName = "Rose VL Deli",
                            BusinessType = "Restaurant",
                            BusinessWebsite = "https://www.facebook.com/JaydenLHV"
                        },
                        new
                        {
                            BusinessId = 36,
                            BusinessName = "Tierra Del Sol Cuisine and Catering",
                            BusinessType = "Food Cart",
                            BusinessWebsite = "http://www.tierradelsolpdx.com/"
                        },
                        new
                        {
                            BusinessId = 37,
                            BusinessName = "Nationale",
                            BusinessType = "Art Gallery",
                            BusinessWebsite = "https://www.nationale.us/"
                        },
                        new
                        {
                            BusinessId = 38,
                            BusinessName = "Froelick Gallery",
                            BusinessType = "Art Gallery",
                            BusinessWebsite = "https://froelickgallery.com/"
                        },
                        new
                        {
                            BusinessId = 39,
                            BusinessName = "Froelick Gallery",
                            BusinessType = "Art Gallery",
                            BusinessWebsite = "https://froelickgallery.com/"
                        },
                        new
                        {
                            BusinessId = 40,
                            BusinessName = "Blackfish Gallery",
                            BusinessType = "Art Gallery",
                            BusinessWebsite = "https://www.blackfish.com/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
